### ISSUE TITLE
erreur import modèle (QGIS3.4, Plugin 1.0)

### ISSUE THREAD

**Issue by brunetfred** [Artelia/Mascaret#25]
Bonjour, 

je n'arrive pas à importer un modèle avec la dernière version du plugin. 
le modèle provient pourtant de la même version du plugin. 
ci dessous le message d'erreur : 
TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "C:/Users/frederic.brunet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\MascPlugDialog.py", line 627, in import_model
    liste = self.mdb.list_schema()
  File "C:/Users/frederic.brunet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mascaret\db\ClassMasDatabase.py", line 1049, in list_schema
    for row in info:
TypeError: 'NoneType' object is not iterable

**Comment by daoum** [comment]
Bonjour,
L'erreur est dans la fonction listant les schémas existant. Il faut donc créé un premier modèle avant d'en importer des nouveaux pour ne pas avoir l'erreur sur cette recherche.
Cette erreur devrait corrigé à la prochaine update.

Cordialement,
